#define ENV_DEBUG "DEBUG"
#define ENV_CALLHANDLER "CALLHANDLER"
#define ENV_STATIC_PID "DEBUG_STATIC_PID"

#define BUF_SIZE 1024
#define FD_OUT 3
#define FD_ERR 4
#define BEGIN_OUT "B_OUT"
#define END_OUT "E_OUT"
#define HEADER_CONST 4278057967
#define TMP_INFO_DIR_PATH "/tmp/debugger"
